require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
